
// Colores disponibles de Tailwind (4.0) – puedes expandir esta lista según necesites
export const coloresTailwind: { name: string; value: string, bgColor: string, border: string }[] = [
    { name: 'Slate', value: 'slate', bgColor: 'bg-slate-500', border: 'border-slate-500' },
    { name: 'Gray', value: 'gray', bgColor: 'bg-gray-500', border: 'border-slate-500' },
    { name: 'Zinc', value: 'zinc', bgColor: 'bg-zinc-500', border: 'border-slate-500' },
    { name: 'Neutral', value: 'neutral', bgColor: 'bg-neutral-500', border: 'border-slate-500' },
    { name: 'Stone', value: 'stone', bgColor: 'bg-stone-500', border: 'border-slate-500' },
    { name: 'Red', value: 'red', bgColor: 'bg-red-500', border: 'border-slate-500' },
    { name: 'Orange', value: 'orange', bgColor: 'bg-orange-500', border: 'border-slate-500' },
    { name: 'Amber', value: 'amber', bgColor: 'bg-amber-500', border: 'border-slate-500' },
    { name: 'Yellow', value: 'yellow', bgColor: 'bg-yellow-500', border: 'border-slate-500' },
    { name: 'Lime', value: 'lime', bgColor: 'bg-lime-500', border: 'border-slate-500' },
    { name: 'Green', value: 'green', bgColor: 'bg-green-500', border: 'border-slate-500' },
    { name: 'Emerald', value: 'emerald', bgColor: 'bg-emerald-500', border: 'border-slate-500' },
    { name: 'Teal', value: 'teal', bgColor: 'bg-teal-500', border: 'border-slate-500' },
    { name: 'Cyan', value: 'cyan', bgColor: 'bg-cyan-500', border: 'border-slate-500' },
    { name: 'Blue', value: 'blue', bgColor: 'bg-blue-500', border: 'border-slate-500' },
    { name: 'Indigo', value: 'indigo', bgColor: 'bg-indigo-500', border: 'border-slate-500' },
    { name: 'Violet', value: 'violet', bgColor: 'bg-violet-500', border: 'border-slate-500' },
    { name: 'Purple', value: 'purple', bgColor: 'bg-purple-500', border: 'border-slate-500' },
    { name: 'Fuchsia', value: 'fuchsia', bgColor: 'bg-fuchsia-500', border: 'border-slate-500' },
    { name: 'Pink', value: 'pink', bgColor: 'bg-pink-500', border: 'border-slate-500' },
    { name: 'Rose', value: 'rose', bgColor: 'bg-rose-500', border: 'border-slate-500' },
];